// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Shree Ram Family Shop",
  category: "Women's clothing store",
  address: "\nDamru Circle, Shop no 23, Mrudul park, 3, Chanakyapuri Rd, opp. Sector 2, Ahmedabad, Gujarat 380061",
  phone: "\n088490 11313",
  email: "",
  website: "https://www.instagram.com/shreeramfamilyshop_abd?igsh=bDN1Z2ZwNHQ5Z2U4",
  mapUrl: "https://www.google.com/maps/place/Shree+Ram+Family+Shop/@23.0764818,72.5372577,17z/data=!3m1!4b1!4m6!3m5!1s0x395e837b4d7fee8f:0x6c743f15a042d6e3!8m2!3d23.0764818!4d72.5372577!16s%2Fg%2F11krbrzy_g?entry=ttu&g_ep=EgoyMDI2MDUyNS4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0764818",
  longitude: "72.5372577",
  rating: "",
  reviewsCount: "50",
  openingHours: "Show open hours for the week",
  logo: null,
  images: ["/images/gmap_1779962572568_0.jpg", "/images/gmap_1779962572623_1.jpg", "/images/gmap_1779962572674_2.jpg", "/images/gmap_1779962572745_3.jpg", "/images/gmap_1779962572797_4.jpg", "/images/gmap_1779962572846_5.jpg", "/images/gmap_1779962572894_6.jpg", "/images/gmap_1779962572945_7.jpg", "/images/gmap_1779962572991_8.jpg", "/images/website_0.jpg"],
  description: "",
  socials: {"instagram":"https://www.instagram.com/accounts/meta_verified/?entrypoint=web_footer&next=%2Fshreeramfamilyshop_abd","facebook":"https://www.facebook.com/help/instagram/261704639352628"},
};

export const aiContent = {
  tagline: "Authentic Gujarati Clothing",
  heroDescription: "Experience the vibrant spirit of Ahmedabad's fashion at Shree Ram Family Shop. Located in the heart of Damru Circle, our store offers an exquisite collection of women's clothing. From traditional to modern, our designs will make you stand out.",
  aboutTitle: "Our Story at Damru Circle",
  aboutText: "Shree Ram Family Shop is nestled in the bustling Damru Circle, bringing the essence of Gujarat's rich textile heritage to our community. Our address at Shop no 23, Mrudul park, 3, Chanakyapuri Rd, opp. Sector 2, Ahmedabad, Gujarat 380061, makes us easily accessible to fashion enthusiasts from all over the city. With a passion for creating unique and stylish clothing, our team is dedicated to providing an unparalleled shopping experience. We take pride in our collection, carefully curated to reflect the beauty of Gujarati culture.",
  services: [
    { icon: "👗", title: "Gujarati Sarees", description: "Exquisite collection of traditional sarees with intricate designs and patterns" },
    { icon: "👜", title: "Lehengas", description: "Stunning lehengas for special occasions, crafted with precision and attention to detail" },
    { icon: "👖", title: "Salwar Kameez", description: "Comfortable and stylish salwar kameez sets, perfect for everyday wear" },
    { icon: "👗", title: "Kurtis", description: "Vibrant and trendy kurtis for the modern woman, available in a range of styles and fabrics" },
    { icon: "👠", title: "Footwear", description: "Beautifully crafted footwear to complement our clothing collection, from traditional to contemporary designs" },
    { icon: "👜", title: "Accessories", description: "Exclusive accessories to enhance your overall look, including jewelry, bags, and more" }
  ],
  whyChooseUs: [
    { icon: "📍", title: "Prime Location", description: "Conveniently located in Damru Circle, making it easy for you to visit us" },
    { icon: "💯", title: "Quality Assurance", description: "We ensure that every product that leaves our store meets the highest standards of quality and craftsmanship" },
    { icon: "👩‍👩‍👧‍👦", title: "Personalized Service", description: "Our experienced staff are always ready to provide personalized advice and assistance to help you find the perfect outfit" },
    { icon: "💸", title: "Competitive Pricing", description: "We offer competitive pricing without compromising on quality, ensuring that you get the best value for your money" }
  ],
  testimonials: [
    { name: "Uma Deshpande", role: "Regular Customer", text: "I recently purchased a beautiful Gujarati saree from Shree Ram Family Shop, and I was impressed by the quality and design. The staff were very helpful in assisting me with my purchase.", rating: 5 },
    { name: "Ujjwal Mehta", role: "Frequent Buyer", text: "I have been shopping at Shree Ram Family Shop for years, and I am always satisfied with their collection and service. Their lehengas are particularly stunning, and I have received many compliments on them.", rating: 5 },
    { name: "Usha Thakkar", role: "New Customer", text: "I visited Shree Ram Family Shop for the first time last week, and I was pleasantly surprised by the variety of clothing they offer. The staff were very friendly and helped me find a beautiful kurti that I love.", rating: 5 }
  ],
  ctaTitle: "Discover Your Style",
  ctaDescription: "Visit us today and explore our extensive collection of women's clothing, carefully curated to meet your fashion needs. Our experienced staff are always ready to assist you in finding the perfect outfit.",
  ctaButtonText: "Explore Now",
  metaDescription: "Gujarati clothing store",
};

export const siteConfig = {
  layout: "dark-futuristic",
  theme: "elegant",
  sections: ["google", "image", "skip", "hamburger/mobile", "whatsapp", "about", "customer", "subtle", "structured", "gallery", "contact", "more", "lazy", "a"],
  heroVariant: "animated-typography",
  navStyle: "transparent-to-solid",
  animationStyle: "blur-in-sharp",
  cardStyle: "rounded-2xl backdrop-blur-md bg-white/5 border border-white/10",
  darkMode: true,
};
